//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var OrderStatus = &struct {
	Pending    postgres.StringExpression
	Processing postgres.StringExpression
	Confirmed  postgres.StringExpression
	Failed     postgres.StringExpression
	Canceled   postgres.StringExpression
}{
	Pending:    postgres.NewEnumValue("PENDING"),
	Processing: postgres.NewEnumValue("PROCESSING"),
	Confirmed:  postgres.NewEnumValue("CONFIRMED"),
	Failed:     postgres.NewEnumValue("FAILED"),
	Canceled:   postgres.NewEnumValue("CANCELED"),
}
