services:
  db:
    container_name: crype-db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${CRYPE_DB_USER}
      POSTGRES_PASSWORD: ${CRYPE_DB_PASSWORD}
      POSTGRES_DB: ${CRYPE_DB_NAME}
    ports:
      - "${CRYPE_DB_PORT}:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${CRYPE_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  data:
